name: Deploy Swagger UI to GitHub Pages

on:
  push:
    branches:
      - main # ваша основная ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Шаг настройки GitHub Pages
      - name: Configure Pages
        uses: actions/configure-pages@v3

      # Шаг загрузки артефактов
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs # папка с openapi.yaml и index.html

      # Шаг деплоя
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
